"""Initial_schema

Revision ID: 05ec4bc15053
Revises: None
Create Date: 2026-08-04 15:09:38.982878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ec4bc15053'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('is_curated_trending', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.drop_index('ix_watch_images_id', table_name='watch_images')
    op.drop_table('watch_images')
    op.drop_index('ix_watches_brand', table_name='watches')
    op.drop_index('ix_watches_id', table_name='watches')
    op.drop_index('ix_watches_name', table_name='watches')
    op.drop_table('watches')
    op.add_column('cart_items', sa.Column('product_id', sa.String(), nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'])
    op.drop_column('cart_items', 'watch_id')
    op.add_column('order_items', sa.Column('product_id', sa.String(), nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_column('order_items', 'watch_id')
    op.add_column('reviews', sa.Column('product_id', sa.String(), nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    op.drop_column('reviews', 'watch_id')
    op.add_column('wishlist', sa.Column('product_id', sa.String(), nullable=False))
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist', 'products', ['product_id'], ['id'])
    op.drop_column('wishlist', 'watch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('watch_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist', 'watches', ['watch_id'], ['id'])
    op.drop_column('wishlist', 'product_id')
    op.add_column('reviews', sa.Column('watch_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'watches', ['watch_id'], ['id'])
    op.drop_column('reviews', 'product_id')
    op.add_column('order_items', sa.Column('watch_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'watches', ['watch_id'], ['id'])
    op.drop_column('order_items', 'product_id')
    op.add_column('cart_items', sa.Column('watch_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'watches', ['watch_id'], ['id'])
    op.drop_column('cart_items', 'product_id')
    op.create_table('watches',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('brand', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(), nullable=True),
    sa.Column('strap_material', sa.VARCHAR(), nullable=True),
    sa.Column('water_resistance', sa.VARCHAR(), nullable=True),
    sa.Column('warranty_years', sa.INTEGER(), nullable=True),
    sa.Column('featured', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watches_name', 'watches', ['name'], unique=False)
    op.create_index('ix_watches_id', 'watches', ['id'], unique=False)
    op.create_index('ix_watches_brand', 'watches', ['brand'], unique=False)
    op.create_table('watch_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('watch_id', sa.VARCHAR(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('image_type', sa.VARCHAR(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watch_images_id', 'watch_images', ['id'], unique=False)
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
